name: Linux Compiler

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-22.04
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create project
        run: |
          cd mp/src
          devtools/bin/vpc /ff +game /mksln Game_FF

      - name: Build project
        env:
          CC: gcc-10
          CXX: g++-10
        run: |
          cd mp/src
          make -f Game_FF.mak

      - name: Pack
        shell: bash
        run: tar cJfv Linux.tar.xz mp/game/FortressForever2013/bin

      - name: Upload product
        uses: actions/upload-artifact@v4
        with:
          name: FF_Linux
          path: Linux.tar.xz
